name: update changelog

on:
  release:
    types: [released]

permissions: {}

jobs:
  update:
    permissions:
      contents: write
    uses: vcian/laravel-db-auditor/.github/workflows/update-changelog.yml@main
